name: kuicktag
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  awesome_icons: ^1.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  gap: ^3.0.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0  # Updated to the latest version
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/
    - assets/business/
    - assets/payment/
    - assets/portfolio/
    - assets/music/
    - assets/content/
    - assets/custom/
    - assets/scaner_images/